security:
    password_hashers:
        App\Entity\Utilisateur: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            provider: app_user_provider
            form_login:
                login_path: login
                default_target_path: / # Rediriger après la connexion
                check_path: login # La route pour soumettre le formulaire de connexion
            logout:
                path: logout
                invalidate_session: true # Invalider la session après la déconnexion

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        # Exemple pour le rôle de modérateur, adaptez vos routes
        # - { path: ^/moderateur, roles: ROLE_MODERATEUR }
        - { path: ^/profile, roles: ROLE_USER }